array([1.0, 1.0, 1.0], dtype=float64)
array([[1.0, 1.0, 1.0],
       [1.0, 1.0, 1.0]], dtype=float64)
array([0.0, 0.0, 0.0], dtype=float64)
array([[0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0]], dtype=float64)
array([[1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0]], dtype=float64)
array([1], dtype=int8)
array([1, 1], dtype=uint8)
array([1, 1, 1], dtype=int16)
array([1, 1, 1, 1], dtype=uint16)
array([1.0, 1.0, 1.0, 1.0, 1.0], dtype=float64)
array([0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0], dtype=float64)
