True
True
True
True
True
True
True
True
True
True
True
180.0
3.141592653589793
3.0
4.0
1.772453850905516
2.718281828459045
1.0
1.0
1.0
1.0
[True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True, True]
[True, True, True, True]
[True, True, True]
