
array([], dtype=uint8)
[]
array([1, 2, 3, 4], dtype=uint8)
[1, 3, 2, 0]

array([], dtype=int8)
[]
array([1, 2, 3, 4], dtype=int8)
[1, 3, 2, 0]

array([], dtype=uint16)
[]
array([1, 2, 3, 4], dtype=uint16)
[1, 3, 2, 0]

array([], dtype=int16)
[]
array([1, 2, 3, 4], dtype=int16)
[1, 3, 2, 0]

array([], dtype=float64)
[]
array([1.0, 2.0, 3.0, 4.0], dtype=float64)
[1, 3, 2, 0]

array([-3, -2, 0, 1], dtype=int8)
[0, 2, 3, 1]
array([-4, -1, 2, 3, 5], dtype=int8)
[3, 1, 4, 2, 0]

array([-3, -2, 0, 1], dtype=int16)
[0, 2, 3, 1]
array([-4, -1, 2, 3, 5], dtype=int16)
[3, 1, 4, 2, 0]

array([-3.0, -2.0, 0.0, 1.0], dtype=float64)
[0, 2, 3, 1]
array([-4.0, -1.0, 2.0, 3.0, 5.0], dtype=float64)
[3, 1, 4, 2, 0]

-3.0

-3.0

-3.0
