ValueError: only ndarrays can be concatenated; failed with object ([1, 2], [3, 4])

ValueError: only ndarrays can be concatenated; failed with object ((1, 2), (3, 4))

ValueError: only ndarrays can be concatenated; failed with object (1, 2, 3)

array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float64)
array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float64)
array([[1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0],
       [7.0, 8.0, 9.0],
       [1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0],
       [7.0, 8.0, 9.0]], dtype=float64)
array([[1.0, 2.0, 3.0, 1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0, 4.0, 5.0, 6.0],
       [7.0, 8.0, 9.0, 7.0, 8.0, 9.0]], dtype=float64)
array([[1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0],
       [7.0, 8.0, 9.0],
       [1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0],
       [7.0, 8.0, 9.0]], dtype=float64)
array([[1.0, 2.0, 3.0, 1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0, 4.0, 5.0, 6.0],
       [7.0, 8.0, 9.0, 7.0, 8.0, 9.0]], dtype=float64)
