array([[0, 1, 2],
       [0, 0, 2]], dtype=uint8)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=uint16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int8)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 0, 1],
       [0, 2, 0]], dtype=uint8)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 1, 2],
       [0, 0, 2]], dtype=uint16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)

==============================
inplace modulo
==============================

array([[0, 1, 2],
       [0, 0, 2]], dtype=uint8)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0, 0, 1],
       [0, 2, 0]], dtype=uint8)
array([[0, 0, 1],
       [0, 0, 0]], dtype=int16)
array([[0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0]], dtype=float64)
array([[0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0]], dtype=float64)
array([[0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0]], dtype=float64)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0, 1, 2],
       [0, 0, 2]], dtype=int16)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
array([[0.0, 1.0, 2.0],
       [0.0, 0.0, 2.0]], dtype=float64)
