array([0, 1, 2, 3, 4, 5], dtype=uint8)
array([[2, 1, 0],
       [4, 5, 3]], dtype=uint8)
array([[1, 3, 4],
       [0, 2, 5]], dtype=uint8)
array([[1, 0, 1],
       [0, 1, 0]], dtype=uint16)

array([0, 1, 2, 3, 4, 5], dtype=int8)
array([[2, 1, 0],
       [4, 5, 3]], dtype=int8)
array([[1, 3, 4],
       [0, 2, 5]], dtype=int8)
array([[1, 0, 1],
       [0, 1, 0]], dtype=uint16)

array([0, 1, 2, 3, 4, 5], dtype=uint16)
array([[2, 1, 0],
       [4, 5, 3]], dtype=uint16)
array([[1, 3, 4],
       [0, 2, 5]], dtype=uint16)
array([[1, 0, 1],
       [0, 1, 0]], dtype=uint16)

array([0, 1, 2, 3, 4, 5], dtype=int16)
array([[2, 1, 0],
       [4, 5, 3]], dtype=int16)
array([[1, 3, 4],
       [0, 2, 5]], dtype=int16)
array([[1, 0, 1],
       [0, 1, 0]], dtype=uint16)

array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0], dtype=float64)
array([[2.0, 1.0, 0.0],
       [4.0, 5.0, 3.0]], dtype=float64)
array([[1.0, 3.0, 4.0],
       [0.0, 2.0, 5.0]], dtype=float64)
array([[1, 0, 1],
       [0, 1, 0]], dtype=uint16)

array([[-3, -4],
       [-1, 1],
       [2, 3]], dtype=int8)
array([[-1, 2, 3],
       [-4, -2, 5]], dtype=int8)

array([[-3, -4],
       [-1, 1],
       [2, 3]], dtype=int16)
array([[-1, 2, 3],
       [-4, -2, 5]], dtype=int16)

array([[-3.0, -4.0],
       [-1.0, 1.0],
       [2.0, 3.0]], dtype=float64)
array([[-1.0, 2.0, 3.0],
       [-4.0, -2.0, 5.0]], dtype=float64)

array([0.0, 1.0, 1.0], dtype=float64)
array([1.0, 0.0, 2.0], dtype=float64)

array([0.0, 1.0, 1.0], dtype=float64)
array([1.0, 0.0, 2.0], dtype=float64)

