
array:
 array([0, 1, 2, 3], dtype=uint8)
exponential: shape (4,)
dtypes match
values match reference

array:
 array([[0, 1],
       [2, 3]], dtype=uint8)
exponential: shape (2, 2)
dtypes match
values match reference

array:
 array([0, 1, 2, 3], dtype=int8)
exponential: shape (4,)
dtypes match
values match reference

array:
 array([[0, 1],
       [2, 3]], dtype=int8)
exponential: shape (2, 2)
dtypes match
values match reference

array:
 array([0, 1, 2, 3], dtype=uint16)
exponential: shape (4,)
dtypes match
values match reference

array:
 array([[0, 1],
       [2, 3]], dtype=uint16)
exponential: shape (2, 2)
dtypes match
values match reference

array:
 array([0, 1, 2, 3], dtype=int16)
exponential: shape (4,)
dtypes match
values match reference

array:
 array([[0, 1],
       [2, 3]], dtype=int16)
exponential: shape (2, 2)
dtypes match
values match reference

array:
 array([0.0, 1.0, 2.0, 3.0], dtype=float64)
exponential: shape (4,)
dtypes match
values match reference

array:
 array([[0.0, 1.0],
       [2.0, 3.0]], dtype=float64)
exponential: shape (2, 2)
dtypes match
values match reference

array:
 array([0.0+0.0j, 1.0+0.0j, 2.0+0.0j, 3.0+0.0j], dtype=complex)
exponential: shape (4,)
dtypes match
values match reference

array:
 array([[0.0+0.0j, 1.0+0.0j],
       [2.0+0.0j, 3.0+0.0j]], dtype=complex)
exponential: shape (2, 2)
dtypes match
values match reference


array:
 array([0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j], dtype=complex)
exponential: shape (4,)
dtypes match
values match reference


array:
 array([[0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j],
       [0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j]], dtype=complex)
exponential: shape (2, 4)
dtypes match
values match reference


array:
 array([[[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]],

       [[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]]], dtype=complex)
exponential: shape (2, 2, 2)
dtypes match
values match reference


array:
 array([[[[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]],

       [[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]]],

       [[[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]],

       [[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]]]], dtype=complex)
exponential: shape (2, 2, 2, 2)
dtypes match
values match reference
