
array:
 array([0, 1, 2, 3], dtype=uint8)
square root: shape (4,)
dtypes match
values match reference

array:
 array([0, 1, 2, 3], dtype=int8)
square root: shape (4,)
dtypes match
values match reference

array:
 array([0, 1, 2, 3], dtype=uint16)
square root: shape (4,)
dtypes match
values match reference

array:
 array([0, 1, 2, 3], dtype=int16)
square root: shape (4,)
dtypes match
values match reference

array:
 array([0.0, 1.0, 2.0, 3.0], dtype=float64)
square root: shape (4,)
dtypes match
values match reference

array:
 array([0.0+0.0j, 1.0+0.0j, 2.0+0.0j, 3.0+0.0j], dtype=complex)
square root: shape (4,)
dtypes match
values match reference

array:
 array([0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j], dtype=complex)
square root: shape (4,)
dtypes match
values match reference
