--- 3D xy ---
array([[[1],
       [2]]], dtype=uint8)
array([[[5],
       [5]]], dtype=uint8)
array([[[9],
       [9]]], dtype=uint8)

--- 3D ij ---
array([[[1]],

       [[2]]], dtype=uint8)
array([[[5]],

       [[5]]], dtype=uint8)
array([[[9]],

       [[9]]], dtype=uint8)

=== 3D Strides ===
--- XY ---
array([[[0, 0, 0],
       [20, 20, 20]]], dtype=uint8)
array([[[5, 5, 5],
       [5, 5, 5]]], dtype=uint8)
array([[[3, 2, 1],
       [3, 2, 1]]], dtype=uint8)
--- IJ ---
array([[[0, 0, 0]],

       [[20, 20, 20]]], dtype=uint8)
array([[[5, 5, 5]],

       [[5, 5, 5]]], dtype=uint8)
array([[[3, 2, 1]],

       [[3, 2, 1]]], dtype=uint8)
