
array:
 array([0, 1, 2, 3, 4, 5, 6, 7], dtype=uint8)
square root: shape (8,)
dtypes match
values match reference

array:
 array([[[0, 1],
       [2, 3]],

       [[4, 5],
       [6, 7]]], dtype=uint8)
square root: shape (2, 2, 2)
dtypes match
values match reference

array:
 array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)
square root: shape (8,)
dtypes match
values match reference

array:
 array([[[0, 1],
       [2, 3]],

       [[4, 5],
       [6, 7]]], dtype=int8)
square root: shape (2, 2, 2)
dtypes match
values match reference

array:
 array([0, 1, 2, 3, 4, 5, 6, 7], dtype=uint16)
square root: shape (8,)
dtypes match
values match reference

array:
 array([[[0, 1],
       [2, 3]],

       [[4, 5],
       [6, 7]]], dtype=uint16)
square root: shape (2, 2, 2)
dtypes match
values match reference

array:
 array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)
square root: shape (8,)
dtypes match
values match reference

array:
 array([[[0, 1],
       [2, 3]],

       [[4, 5],
       [6, 7]]], dtype=int16)
square root: shape (2, 2, 2)
dtypes match
values match reference

array:
 array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], dtype=float64)
square root: shape (8,)
dtypes match
values match reference

array:
 array([[[0.0, 1.0],
       [2.0, 3.0]],

       [[4.0, 5.0],
       [6.0, 7.0]]], dtype=float64)
square root: shape (2, 2, 2)
dtypes match
values match reference

array:
 array([0.0+0.0j, 1.0+0.0j, 2.0+0.0j, 3.0+0.0j, 4.0+0.0j, 5.0+0.0j, 6.0+0.0j, 7.0+0.0j], dtype=complex)
square root: shape (8,)
dtypes match
values match reference

array:
 array([[[0.0+0.0j, 1.0+0.0j],
       [2.0+0.0j, 3.0+0.0j]],

       [[4.0+0.0j, 5.0+0.0j],
       [6.0+0.0j, 7.0+0.0j]]], dtype=complex)
square root: shape (2, 2, 2)
dtypes match
values match reference


array:
 array([0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j], dtype=complex)
square root: shape (4,)
dtypes match
values match reference


array:
 array([[0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j],
       [0.0+0.0j, 0.0+1.0j, 2.0+2.0j, 3.0-3.0j]], dtype=complex)
square root: shape (2, 4)
dtypes match
values match reference


array:
 array([[[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]],

       [[0.0+0.0j, 0.0+1.0j],
       [2.0+2.0j, 3.0-3.0j]]], dtype=complex)
square root: shape (2, 2, 2)
dtypes match
values match reference
